### ISSUE TITLE
wrapPrototype is not a function

### ISSUE THREAD

**Issue by targunp** [braintree/braintree_node#102]
### General information

* SDK/Library version: 2.1.3
* Environment: Sandbox
* Language, language version, and OS: Node v8.0.0 on MacOS 10.12.6

### Issue description

```
Error initializing middleware
TypeError: wrapPrototype is not a function
    at Object.<anonymous> (/Users/phil/Projects/api/node_modules/braintree/lib/braintree/http.js:156:25)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/phil/Projects/api/node_modules/braintree/lib/braintree/braintree_gateway.js:3:12)
    at Module._compile (module.js:569:30)
```

### Possible Fix

Looks like npm is unable to install **wrap-promise**

current package.json:

`"wrap-promise": "github:braintree/wrap-promise#1.1.0",`

should be:

`"@braintree/wrap-promise": "git+https://github.com/braintree/wrap-promise.git",`

all the requires need to also be updated like so:

`let wrapPrototype = require('@braintree/wrap-promise').wrapPrototype;`

**Comment by crookedneighbor** [comment]
What version of `npm` are you using? You posted Node v8, so I'm assuming npm v5. There are some known issues with [npm v5.x.x regarding github dependencies](https://github.com/npm/npm/issues/16839). 

We just recently published [wrap-promise as a scoped package](https://www.npmjs.com/package/@braintree/wrap-promise) and the next release will include the change to switch from a Github dependency to the npm module instead. 

I see you opened a PR to do this. I'll address a few changes that need to be made there.

**Comment by crookedneighbor** [comment]
Closed with https://github.com/braintree/braintree_node/pull/103

**Comment by MJLang** [comment]
Sorry to bother with this, but whats the ETA for this release?

**Comment by crookedneighbor** [comment]
Version 2.2.0 is now out, which includes this fix. Thanks for your patience!
