### ISSUE TITLE
How to use Braintree SDK with Firebase Cloud Functions?

### ISSUE THREAD

**Issue by Kangtle** [braintree/braintree_node#114]
### General information

* SDK/Library version: 
* Environment: 
* Language, language version, and OS: 

### Issue description

I am trying to deploy Braintree server into Firebase cloud store.
I have some issue in it.

client_token | error { unexpectedError: Unexpected request error: Error: getaddrinfo ENOTFOUND api.sandbox.braintreegateway.com api.sandbox.braintreegateway.com:443     at Object.UnexpectedError (/user_code/node_modules/braintree/lib/braintree/exceptions.js:7:15)     at ClientRequest.theRequest.on.err (/user_code/node_modules/braintree/lib/braintree/http.js:159:32)     at emitOne (events.js:96:13)     at ClientRequest.emit (events.js:188:7)     at TLSSocket.socketErrorListener (_http_client.js:309:9)     at emitOne (events.js:96:13)     at TLSSocket.emit (events.js:188:7)     at connectErrorNT (net.js:1021:8)     at _combinedTickCallback (internal/process/next_tick.js:80:11)     at process._tickDomainCallback (internal/process/next_tick.js:128:9) name: 'unexpectedError', type: 'unexpectedError' }
-- | --

Please help me

**Comment by Kangtle** [comment]
Thank you for your reply.
I just sent a ticket to your support team

Best regards.
