### ISSUE TITLE
Call gateway.transaction.sale using card number 4023898493988028 got Server Error

### ISSUE THREAD

**Issue by ericxinzhang** [braintree/braintree_node#116]
## General information

* SDK/Library version: 2.30.
* Environment: Sandbox
* Language, language version, and OS: Node v8.7.0 on Windows 7

### Error Summary
When testing payment using the card number 4023898493988028 that can be used to simulate an open dispute (refer to https://developers.braintreepayments.com/reference/general/testing/node#disputes), got Server Error and null as result.

### Step to reproduce
1. Clone https://github.com/braintree/braintree_express_example
2. Open package.json and update braintree to version 2.3.0 (actually the original version 1.30.0 used by the example got same error)
3. Run npm install, copy example.env as .env and fill in the braintree sandbox account details
4. Run npm start, and then test the API through UI, by pasting card number 4023898493988028

#### Code Snippet
```
gateway.transaction.sale({
    amount: amount,   // '10.0'
    paymentMethodNonce: nonce,
    options: {
      submitForSettlement: true
    }
  }, function (err, result) {
    console.error(err); 
    /* err as follows, and result is null
{ serverError: Server Error
    at Object.ServerError (C:\js-apps\braintree_express_example\node_modules\braintree\lib\braintree\exceptions.js:7:15)
    at Http.checkHttpStatus (C:\js-apps\braintree_express_example\node_modules\braintree\lib\braintree\http.js:31:37)
    at Http.<anonymous> (C:\js-apps\braintree_express_example\node_modules\@braintree\wrap-promise\wrap-promise.js:17:33)
    at IncomingMessage.response.on (C:\js-apps\braintree_express_example\node_modules\braintree\lib\braintree\http.js:91:28)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) name: 'serverError', type: 'serverError' }
*/
});
```

**Comment by crookedneighbor** [comment]
I was able to process this card number with my sandbox account. I tried both on a Mac and Windows 10 machine and was successful on both.

This is more likely to be an issue with your account than with the SDK. I recommend contacting our support team so we can look into your account and see if anything is amiss.  https://developers.braintreepayments.com/forms/contact
