### ISSUE TITLE
Find Customer: TypeError: Request path contains unescaped characters

### ISSUE THREAD

**Issue by yomagic** [braintree/braintree_node#143]
### General information

* SDK/Library version: braintree@2.11.0
* Environment: Sandbox
* Language, language version, and OS: Node v8.11.3

### Issue description
I am trying to write code which will decide whether to create a customer or update an existing one. For this I am passing a string id in the request body like so: user.documentId='0RVEncecE4YgTCtxifIn'
When I call:
 gateway.customer.find(user.documentId, function(err, customer) {}

I get the following error in Firebase:
customer.find error is:  TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:52:11)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:206:15)
    at Promise (/user_code/node_modules/braintree/lib/braintree/http.js:82:31)
    at Http.request (/user_code/node_modules/braintree/lib/braintree/http.js:81:12)
    at Http.<anonymous> (/user_code/node_modules/braintree/node_modules/@braintree/wrap-promise/wrap-promise.js:17:33)
    at Http.get (/user_code/node_modules/braintree/lib/braintree/http.js:42:17)
    at Http.<anonymous> (/user_code/node_modules/braintree/node_modules/@braintree/wrap-promise/wrap-promise.js:17:33)
    at CustomerGateway.find (/user_code/node_modules/braintree/lib/braintree/customer_gateway.js:42:30)
    at CustomerGateway.<anonymous> (/user_code/node_modules/braintree/node_modules/@braintree/wrap-promise/wrap-promise.js:17:33)

**Comment by crookedneighbor** [comment]
I've seen this error occur when extra spaces are accidentally added to environmental variables for the gateway configuration. Can you double check that your API keys do not contain any extra space characters?

A merchant in the past with this issue was using kubernetes to deploy their app and the encrypted variables included the new line character. (which, obviously, makes the credentials incorrect)

**Comment by crookedneighbor** [comment]
Fairly certain that this is the issue you were facing, so I'm going to close this. Comment here and I can re-open it if you still need help.
