### ISSUE TITLE
Authorisation Error 

### ISSUE THREAD

**Issue by saurabh2590** [braintree/braintree_node#144]
### General information

* SDK/Library version: 2.11.0
* Environment: Production
* Language, language version, and OS: Node v8.11.3 / ubuntu 16.0.4 (with typescript)

### Issue description
- I followed the getting started guide to the point by setting my client & setting my server. https://developers.braintreepayments.com/start/overview
- My code perfectly fine with my sandbox environment & I was able to make sales and make transactions for PayPal integration.
- However, in the production environment, I am getting always authorization error.
- I am using my personal account for my sandbox integration, however user my client's account for my production integration.
- I made sure that API keys I am using production environment have permissions to create customer and to create transaction sales.
- Below is the code which worked for my server side in the sandbox environment, however same code gives an error in the production mode.
```
export default class BrainTreeResolver {
    public brainTreeGateway: any;

    constructor() {
        this.brainTreeGateway = braintree.connect({
            environment:  braintree.Environment.Production,
            merchantId:   'prod_merchant_id',
            publicKey:    'prod_public_key',
            privateKey:   'prod_private_key'
        });
    }

    public async getClientToken(request: Request, response: Response) {
        const {customerId} = request.query;
        const data = await this.brainTreeGateway.clientToken.generate({
            ...(customerId && {customerId})
        });
        return response.status(200).send(data);
    }

    public async checkout(request: Request, response: Response) {
        const {paymentMethodNonce, amount, email} = request.body;
        if (email) {
            try {
                const {customer: {id: customerId}} = await this.brainTreeGateway.customer.create({
                    email,
                    paymentMethodNonce
                });
                const data = await this.brainTreeGateway.transaction.sale({
                    customerId,
                    amount: parseFloat(amount).toFixed(2),
                    options: {
                        submitForSettlement: true
                    }
                });
                return response.status(200).send({...data, customerId});
            } catch (e) {
                console.log(e);
                return response.status(200).send({success: false});
            }
        } else {
            const data = await this.brainTreeGateway.transaction.sale({
                paymentMethodNonce,
                amount: parseFloat(amount).toFixed(2),
                options: {
                    submitForSettlement: true
                }
            });
            return response.status(200).send({...data});
        }
    }
}
```
- Here is the error
```
at Object.AuthorizationError (/home/ubuntu/cris-api-v2/node_modules/braintree/lib/braintree/exceptions.js:7:15)
    at Http.checkHttpStatus (/home/ubuntu/cris-api-v2/node_modules/braintree/lib/braintree/http.js:27:37)
    at Http.<anonymous> (/home/ubuntu/cris-api-v2/node_modules/@braintree/wrap-promise/wrap-promise.js:17:33)
    at IncomingMessage.response.on (/home/ubuntu/cris-api-v2/node_modules/braintree/lib/braintree/http.js:91:28)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by crookedneighbor** [comment]
Since everything is working fine in sandbox, I don't think the issue is going to be with the SDK itself. [Please contact our support team so we can better troubleshoot your integration](https://articles.braintreepayments.com/forms/contact)

**Comment by leogoesger** [comment]
? I am seeing the same error, I can reproduce it about 50% of the time.

**Comment by crookedneighbor** [comment]
@leogoesger Please contact our support team so we can inspect your account. https://github.com/braintree/braintree_php/blame/master/lib/Braintree/TransactionGateway.php#L104

**Comment by crookedneighbor** [comment]
Posted the wrong link from my clipboard. Meant to direct you to https://help.braintreepayments.com/
