### ISSUE TITLE
Transaction.Sale Sandbox Cannot read property 'apiErrorResponse' of undefined

### ISSUE THREAD

**Issue by hindsricardo** [braintree/braintree_node#45]
While using sandbox and creating a transaction.

/Users/hindsricardo/Google_Drive/upon_imac/node_modules/braintree/lib/braintree/gateway.js:23
      if (response.apiErrorResponse) {
                  ^
TypeError: Cannot read property 'apiErrorResponse' of undefined
    at /Users/hindsricardo/Google_Drive/upon_imac/node_modules/braintree/lib/braintree/gateway.js:23:19
    at /Users/hindsricardo/Google_Drive/upon_imac/node_modules/braintree/lib/braintree/http.js:103:20
    at Parser.<anonymous> (/Users/hindsricardo/Google_Drive/upon_imac/node_modules/braintree/node_modules/xml2js/lib/xml2js.js:138:18)
    at Parser.EventEmitter.emit (events.js:95:17)
    at Object.saxParser.onerror (/Users/hindsricardo/Google_Drive/upon_imac/node_modules/braintree/node_modules/xml2js/lib/xml2js.js:51:24)
    at emit (/Users/hindsricardo/Google_Drive/upon_imac/node_modules/braintree/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
    at error (/Users/hindsricardo/Google_Drive/upon_imac/node_modules/braintree/node_modules/xml2js/node_modules/sax/lib/sax.js:644:3)
    at strictFail (/Users/hindsricardo/Google_Drive/upon_imac/node_modules/braintree/node_modules/xml2js/node_modules/sax/lib/sax.js:662:22)
    at Object.write (/Users/hindsricardo/Google_Drive/upon_imac/node_modules/braintree/node_modules/xml2js/node_modules/sax/lib/sax.js:1000:11)
    at Parser.exports.Parser.Parser.parseString (/Users/hindsricardo/Google_Drive/upon_imac/node_modules/braintree/node_modules/xml2js/lib/xml2js.js:145:29)

**Comment by ryanjpodonnell** [comment]
Hello @hindsricardo,

It seems like we need more context on what you are trying to do before we can diagnose the problem. We would like to rule out an issue with your Sandbox integration. If you can reach out to us at support@braintreepayments.com we can better help you with this specific issue.

Ryan O'Donnell
Braintree Developer

**Comment by hindsricardo** [comment]
This issue is resolved now. The issue was the custom fields were returning
an error but it didn't throw a return error in the console for the
gateway.sale

Thanks,

Ricardo

**Comment by ryanjpodonnell** [comment]
Hey Ricardo,

Glad you were able to figure out and fix the issue.

Best,
Ryan
