### ISSUE TITLE
Token generation issue

### ISSUE THREAD

**Issue by nirbhaykumar007** [braintree/braintree_node#95]
We are trying to create token at server end by hitting webservices. It generates token successfully and sometime it generates error as below:

ERROR: 
{ unexpectedError: Unexpected request error: Error: getaddrinfo EAI_AGAIN api.sandbox.braintreegateway.com:443
    at Object.UnexpectedError (/var/www/html/TenFourRepo/node_modules/braintree/lib/braintree/exceptions.js:7:15)
    at ClientRequest.theRequest.on.err (/var/www/html/TenFourRepo/node_modules/braintree/lib/braintree/http.js:133:30)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1020:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9) name: 'unexpectedError', type: 'unexpectedError' }

**Comment by bluk** [comment]
The [EAI_AGAIN error](https://linux.die.net/man/3/getaddrinfo) ("The name server returned a temporary failure indication. Try again later.") seems to indicate that there is an issue in your environment with DNS.  For instance, it could be an unstable Internet connection or a proxy-related issue. You can try contacting [Braintree support](https://articles.braintreepayments.com) but I would also try contacting your service provider for support since it seems related to your environment.

**Comment by rishabh-deligence** [comment]
I'm also facing the issue.
Did you find the solution? 
I've deployed my code to "generate client token" and "transaction sale" on the firebase cloud function.

**Comment by crookedneighbor** [comment]
Bluk's answer is still correct. You may reach out to Braintree support, but the problem is more likely with your service provider.
